version: '3.8'
services:
  stats-server:
    build: statistic
    image: ewm-statistic-image
    container_name: ewm-statistic-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-statistic-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: main
    container_name: ewm-main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
